language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ardayavas/react-test -f Dockerfile.dev .

script:
 - docker run -e CI=true ardayavas/react-test npm run test